version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432
  redis:
    image: 'redis:latest'
    ports:
      - 6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    links: 
      - client
      - server:api
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
# issue on docker toolbox with windows, to fix
#    volumes:
#        - /app/node_modules
#        - ./client:/app
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - '5000:5000'
    links:
      - redis
      - postgres
# issue on docker toolbox with windows, to fix
#     volumes:
#        - /app/node_modules
#        - ./server:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
# issue on docker toolbox with windows, to fix
#    volumes:
#        - /app/node_modules
#        - ./worker:/app
