version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432
  redis:
    image: 'redis:latest'
    ports:
      - 6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '3050:80'
    links: 
      - client
      - server:api
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:3000'
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - '5000:5000'
    links:
      - redis
      - postgres
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
